### PR TITLE
Read i18nDescriptionKey from Validator options.

### LINKED ISSUE #10: Translating 'description' key of validator
Hey,

Is there any plan on allowing translations of the description key? Something like this:

```
username: validator('presence', {
    presence: true,
    description: 'key.to.translation.username'
})
```

and in the `getDescriptionFor` do:

```
getDescriptionFor(attribute, options = {}) {
  const i18n = this.get('i18n');
  let key = `${this.get('prefix')}.description`;

  if (!Ember.isEmpty(options.description)) {
      key = options.description;
  }

  if (i18n && i18n.exists(key)) {
    return unwrap(i18n.t(key, options));
  }

  return this._super(...arguments);
}
```

Let me know what you think or if there's any other recommended way of translating the description.

### PR DESCRIPTION
**Pull request by caalle**
Fixes #10 

Allow translation of Validator descriptions by setting `i18nDescriptionKey`. Not entirely sure about the key name.

Let me know what you think.

### CODE REVIEW

**Comment by jasonmit** [comment]
Ignore houndci, I'll fix that soon.  Maybe lets change `i18nDescriptionKey` to just `descriptionKey`, thoughts?

Looks good and thanks for doing this :+1:

**Comment by caalle** [comment]
Sounds good, that will make it easier to type as well. Updated the pull request.

**Comment by jasonmit** [comment]
Published under 2.3.0.  Thanks again @caalle :+1:

**Comment by caalle** [comment]
Nice! Thank you for the quick action.

**Pull request merged**
