### PR TITLE
Fixes #16

### LINKED ISSUE #16: Add messageKey
Context: https://github.com/offirgolan/ember-cp-validations/issues/192#issuecomment-220857103

### PR DESCRIPTION
**Pull request by jelhan**

### CODE REVIEW

**Comment by jasonmit** [comment]
Versioned as 2.5.0 - thanks!

**Comment by offirgolan** [comment]
Thanks for taking the time to put this together @jelhan! 

@jasonmit do you think you can port this over to `ember-intl-cp-validations`? 😺

**Comment by jasonmit** [comment]
👍 @offirgolan

**Comment by jasonmit** [comment]
Done

**Comment by offirgolan** [comment]
Fantastic! Thanks @jasonmit 😸

**Pull request merged**
